name: deploy dockerized web app
on:
  push:
    branches: [ main ]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.KEY }}
          USER: ${{ secrets.USERNAME }}
          IP: ${{ secrets.HOST }}
        run: |
          eval $(ssh-agent)
          echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $IP > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh $USER@$IP "cd hello-world && \
            git pull && \
            docker-compose up -d --build"
